// Generated by Claude with the Yahtzee message added by me (with help by Claude to use its CSS)

// Yahtzee Dice Roller
// Rolls five 6-sided dice using random numbers, updates each die's pips,
// fills in the read-only scorecard fields, and totals the result.

const NUMBER_OF_DICE = 5;
const SIDES_PER_DIE = 6;
const FORCE_YAHTZEE = false; //Testing the Yahtzee message I added.

/**
 * Returns a random integer between 1 and SIDES_PER_DIE, inclusive.
 */
function rollOneDie() {
  if (FORCE_YAHTZEE) return 1;
  return Math.floor(Math.random() * SIDES_PER_DIE) + 1;
}

/**
 * Rolls all five dice, updates the dice faces and the scorecard,
 * and briefly animates each die to make the roll feel physical.
 */
function rollAllDice() {
  let total = 0;
  const roll = [];
  for (let dieNumber = 1; dieNumber <= NUMBER_OF_DICE; dieNumber++) {
    const result = rollOneDie();
    total += result;
    roll.push(result);
    const dieElement = document.querySelector(`.die[data-die="${dieNumber}"]`);
    const valueField = document.getElementById(`value-${dieNumber}`);

    dieElement.setAttribute("data-value", result);
    valueField.value = result;

    // Retrigger the tumble animation even on repeated identical rolls.
    dieElement.classList.remove("is-rolling");
    // Forcing a reflow lets the animation restart cleanly.
    void dieElement.offsetWidth;
    dieElement.classList.add("is-rolling");
  }

  document.getElementById("value-total").value = total;
  let yahtzee = true;
  for (let i = 1; i < roll.length; i++) {
    if (roll[i] !== roll[0]) {
      yahtzee = false;
      break;
    }
  }
  if (yahtzee) {
    showYahtzeeMessage(roll[0]);
  }
}

const rollButton = document.getElementById("roll-button");

rollButton.addEventListener("keydown", (e) => {
  if (e.key === "Enter") rollButton.classList.add("is-pressed");
});

rollButton.addEventListener("keyup", (e) => {
  if (e.key === "Enter") rollButton.classList.remove("is-pressed");
});

const yahtzeeDialog = document.getElementById("yahtzee-dialog");
const yahtzeeMessage = document.getElementById("yahtzee-message");

function showYahtzeeMessage(value) {
  yahtzeeMessage.textContent = `Yahtzee! All five dice show ${value}.`;
  setTimeout(() => {if (!yahtzeeDialog.open) yahtzeeDialog.showModal();}, 600);
}